//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGIS_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int App_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> APM_ID { get; set; }
        public int GIS_Environment_ID { get; set; }
        public string URL_En { get; set; }
        public string URL_Fr { get; set; }
        public string Description { get; set; }
        public int TechSupport1 { get; set; }
        public Nullable<int> TechSupport2 { get; set; }
        public Nullable<int> ClientContact1 { get; set; }
        public Nullable<int> ClientContact2 { get; set; }
        public string DevOps_Link_En { get; set; }
        public string DevOps_Link_Fr { get; set; }
        public string Technical_Doc_Link { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
        public string Last_UpdatedBy { get; set; }
    
        public virtual Client_Contact Client_Contact { get; set; }
        public virtual Client_Contact Client_Contact1 { get; set; }
        public virtual GIS_Environment GIS_Environment { get; set; }
        public virtual Tech_Support Tech_Support { get; set; }
        public virtual Tech_Support Tech_Support1 { get; set; }
    }
}
