//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGIS_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIS_Server
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIS_Server()
        {
            this.Softwares = new HashSet<Software>();
        }
    
        public int Server_ID { get; set; }
        public string Name { get; set; }
        public string FQDN { get; set; }
        public short Zone_ID { get; set; }
        public string IP_Address { get; set; }
        public int gis_environment_ID { get; set; }
        public short OS { get; set; }
        public int Diskspace_GB { get; set; }
        public short RAM_GB { get; set; }
        public Nullable<short> CPU { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
        public string Last_Updated_By { get; set; }
    
        public virtual GIS_Environment GIS_Environment { get; set; }
        public virtual Network_Zone Network_Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Software> Softwares { get; set; }
        public virtual OS OS1 { get; set; }
    }
}
