//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGIS_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIS_Server
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIS_Server()
        {
            this.Software = new HashSet<Software>();
            this.NetworkShare = new HashSet<NetworkShare>();
        }
    
        public int Server_ID { get; set; }
        public string Name { get; set; }
        public string FQDN { get; set; }
        public short Zone_ID { get; set; }
        public string IP_Address { get; set; }
        public short Region_ID { get; set; }
        public int gis_environment_ID { get; set; }
        public short OS_ID { get; set; }
        public int Diskspace_GB { get; set; }
        public short RAM_GB { get; set; }
        public short CPU { get; set; }
        public string SSL_IssuedTo { get; set; }
        public string SSL_IssuedBy { get; set; }
        public Nullable<System.DateTime> SSL_ExpiryDate { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
        public string Last_Updated_By { get; set; }
        public string Port_in_Use { get; set; }
        public string Firewall_Rules { get; set; }
    
        public virtual DFO_Region DFO_Region { get; set; }
        public virtual OS OS { get; set; }
        public virtual Network_Zone Network_Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Software> Software { get; set; }
        public virtual GIS_Environment GIS_Environment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NetworkShare> NetworkShare { get; set; }
    }
}
